#!/bin/zsh

# Symlinks MUST have ABSOLUTE PATH

ZSH_REPO_NAME=".zshpc"

# We manually create the folder in order to avoid copying 
# files to the repo and letting other plugins install on the same folder
mkdir -p "$HOME/.config/zsh"

ln -sf "$HOME/$ZSH_REPO_NAME/.zshrc" "$HOME/.zshrc"
ln -sf "$HOME/$ZSH_REPO_NAME/.p10k.zsh" "$HOME/.p10k.zsh"

for i in "$HOME"/"$ZSH_REPO_NAME"/.config/zsh/*; do
    [[ -e "$i" ]] || break

    aux=$(echo "$i" | grep -o "[^/]*$")
    ln -sf "$i" "$HOME/.config/zsh/$aux"
done